### ISSUE TITLE
ColorNext can not put string value. (^_^;;

### ISSUE THREAD

**Issue by callmekohei** [lubgr/hlgdb#1]
Hello! I'm `callmekohei`!

Thank you for your useful code!

# Problems summary
ColorNext can not put string value.

like this ...
```python
class ColorNext(gdb.Command):
    """Do the same as the standard 'next' command, but colorize the output."""

    def __init__(self):
        gdb.Command.__init__(self                     \
                , name            = 'n'               \
                , command_class   = gdb.COMMAND_USER  \
                , completer_class = gdb.COMPLETE_NONE \
                , prefix          = True)

    def invoke(self, arg, from_tty):
            output = gdb.execute(command='next',from_tty=False, to_string=True)
            print(output is None)
            print(output == '')
```
result
```
(gdb)  n
6	    n = 2;
False
True
```

## Expected
```
(gdb)  n
False
False
```

## Environment Information

 * GDB :
```
$ gdb --version
GNU gdb (GDB) 8.0.1
```

 * OS :
```
tmp$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
```

 * Python :
```
$ python2 --version
Python 2.7.14

/// gdb use
/usr/local/opt/python/bin/python2.7
```

**Comment by lubgr** [comment]
Thanks for reporting this issue! I can confirm this behavior, same gdb version, same Python2 version, OS is Archlinux. The issue is identical to the `ColorStep` command - though `ColorList` works as expected, which is weird because all three invocations of `gdb.execute` are identical. Seems that the output of these commands isn't handled in a uniform way by the python API.

**Comment by callmekohei** [comment]
Thank you for your reply!

Hmm....

I try again it.

So `list` work well, but `next or step` does not  work well. (^_^;;;

like this
![untitled](https://user-images.githubusercontent.com/17691683/34844639-7c3b0706-f755-11e7-9254-f973185715b8.gif)

**Comment by callmekohei** [comment]
`.gdbinit`
```
set startup-with-shell off

python import sys; print(sys.executable)
source /Users/callmekohei/tmp/hlgdb.py
```

`hlgdb.py`
```python
from pygments.lexers import CLexer, TextLexer



    def getLexer(self):
        languageStr = gdb.execute('show language', False, True)

        if languageStr.find('c') != -1:
            return CLexer()
        else:
            return TextLexer()
```

**Comment by callmekohei** [comment]
I seems to think python's gdb lib's bug.

I write this.

see also: https://bugs.python.org/issue32531
